apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KCSJhdXRocyI6IHsNCiAgICAgICAgICAgICAgICAiZ2hjci5pbyI6IHsNCiAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiWVdKbFoybHVlV0Z1T21kb2NGOVVTMkZNY0cxa1dGTlpVMjlwZG5WTlJHMTBVV3BZWkcweFltTmtOVll5VVd3eFJWaz0iDQogICAgICAgICAgICAgICAgfQ0KICAgICAgICB9LA0KCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLA0KCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwNCgkicGx1Z2lucyI6IHsNCgkJIi14LWNsaS1oaW50cyI6IHsNCgkJCSJlbmFibGVkIjogInRydWUiDQoJCX0sDQoJCSJhaSI6IHsNCgkJCSJob29rcyI6ICJidWlsZCxidWlsZHggYnVpbGQscnVuLGNvbXBvc2UiDQoJCX0sDQoJCSJjb21wb3NlIjogew0KCQkJImhvb2tzIjogImxvZ3MsY29tcG9zZSBsb2dzLGNvbXBvc2UgYXR0YWNoLGNvbXBvc2UgdXAiDQoJCX0sDQoJCSJkZWJ1ZyI6IHsNCgkJCSJob29rcyI6ICJleGVjIg0KCQl9LA0KCQkic2NvdXQiOiB7DQoJCQkiaG9va3MiOiAicHVsbCxidWlsZHggYnVpbGQiDQoJCX0NCgl9LA0KCSJmZWF0dXJlcyI6IHsNCgkJImhvb2tzIjogInRydWUiDQoJfQ0KfQ==
type: kubernetes.io/dockerconfigjson
